// Builds registry.json + src/registry/__index__.tsx from src/registry/index.ts.
// Afterwards `shadcn build` reads registry.json and emits public/r/*.json.
//
// Run with:  bun run ./src/scripts/build-registry.mts
// Or via the package.json script:  bun run registry:build
//
// Adapted (and trimmed) from yash14.com's build-registry pipeline (MIT).

import { promises as fs } from "node:fs";
import path from "node:path";

import { type Registry, registrySchema } from "shadcn/schema";

import { registry } from "@/registry/index";

const REGISTRY_PATH = path.join(process.cwd(), "src/registry");

// Default author stamped onto every registry item that doesn't set its own.
// 👉 Edit this to your real name/email.
const DEFAULT_AUTHOR = "yash14 <hello@yash14.com>";

/**
 * Generate registry.json (consumed by `shadcn build`) and
 * src/registry/__index__.tsx (used by the site to render live previews).
 */
async function buildRegistry(
  reg: Registry & { name: string; homepage: string },
) {
  let index = `/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import * as React from "react";

export const Index: Record<string, any> = {`;

  for (const item of reg.items) {
    if (!Array.isArray(item.files) || !item.files?.length) {
      continue;
    }

    const componentFilePath = item.files[0].path;
    const componentPath = componentFilePath.startsWith("src/")
      ? componentFilePath.replace("src/", "@/")
      : `@/registry/${componentFilePath}`;

    index += `
  "${item.name}": {
    name: "${item.name}",
    description: "${item.description ?? ""}",
    type: "${item.type}",
    files: [${item.files.map((file) => {
      const filePath = file.path.startsWith("src/")
        ? file.path
        : `src/registry/${file.path}`;
      return `{
        path: "${filePath}",
        type: "${file.type}",
        target: "${file.target ?? ""}",
      }`;
    })}],
    component: React.lazy(async () => {
      const mod = await import("${componentPath}");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ${JSON.stringify(item.categories)},
    meta: ${JSON.stringify(item.meta)},
  },`;
  }

  index += `
};
`;

  const registryJSON = JSON.stringify(
    {
      $schema: "https://ui.shadcn.com/schema/registry.json",
      name: reg.name,
      homepage: reg.homepage,
      items: reg.items
        .filter((item) => item.type !== "registry:example")
        .map((item) => ({
          ...item,
          author: item.author ?? DEFAULT_AUTHOR,
          files:
            item.files?.map((file) =>
              file.path.startsWith("src/")
                ? file
                : { ...file, path: `src/registry/${file.path}` },
            ) ?? [],
        })),
    },
    null,
    2,
  );

  console.log("📦 Building registry.json...");
  await fs.writeFile(
    path.join(process.cwd(), "registry.json"),
    registryJSON,
    "utf8",
  );

  console.log("📦 Building src/registry/__index__.tsx...");
  await fs.writeFile(path.join(REGISTRY_PATH, "__index__.tsx"), index, "utf8");
}

try {
  const result = registrySchema.safeParse(registry);

  if (!result.success) {
    console.error(result.error);
    process.exit(1);
  }

  await buildRegistry(registry);

  console.log("✅ Registry build complete!");
} catch (error) {
  console.error(error);
  process.exit(1);
}
