/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import * as React from "react";

export const Index: Record<string, any> = {
  "icon-swap": {
    name: "icon-swap",
    description: "Animate icon swaps with scale, blur, and fade transitions.",
    type: "registry:component",
    files: [
      {
        path: "src/registry/components/icon-swap/icon-swap.tsx",
        type: "registry:component",
        target: "@components/icon-swap.tsx",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/icon-swap/icon-swap.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
    categories: ["effects"],
    meta: undefined,
  },
};
